spring.application.name=bookshop-mvc

spring.datasource.url=jdbc:mysql://localhost:3306/bookshop_bootcamp16
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update